# Generated by Django 5.1.3 on 2024-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_booklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, upload_to="book_images"),
        ),
    ]
